[package]
name = "token_escrow"
version = "0.1.0"
edition = "2018"

[dependencies]
anchor-lang = "0.23.0"
anchor-spl = "0.23.0"

[features]
default = ["test-bpf"]

[dev-dependencies]
anchor-lang = { version = "0.23.0", features = ["test-bpf"] }